#
FROM node:18-alpine AS builder
WORKDIR /app


COPY package*.json ./


RUN npm install --production --no-audit --prefer-offline --legacy-peer-deps --ignore-scripts


COPY . .


RUN npm run build


FROM node:18-alpine
WORKDIR /app


COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/.next ./.next  
COPY --from=builder /app/public ./public  


EXPOSE 3000


CMD ["npm", "start"]